### ISSUE TITLE
pymandelcli not zooming to the right places

### ISSUE THREAD

**Issue by mz1119** [semuconsulting/PyMandel#2]
For some reason, when I tried recreating the animation from the README using pymandeCLI, the pictures quickly started zooming into an unexpected part of the Mandelbrot set and quickly turned all black. I tried the same offsets in the pymandel app and it worked fine. 

After installation, I typed this into the command line: 

_pymandelcli filename="zoom" width=400 height=300 frames=178 zoom=0.75 zoominc=1.2 zxoffset=-0.743643887037158704752191506114774 zyoffset=0.131825904205311970493132056385139 theme="Colorcet_CET_C1"_

And here's what I got:

Attatched are the 16th and 24th generated images to show that its not zooming right. 

![zoom_016](https://user-images.githubusercontent.com/40515363/119082052-215d1e00-b9b2-11eb-936f-64108406c494.png)
![zoom_024](https://user-images.githubusercontent.com/40515363/119082053-215d1e00-b9b2-11eb-9c37-f77e5a461891.png)

This could totally be my own mistake somewhere from lack of experience, but if its a bug hopefully this will alert you of it. I'm on MacOS Big Sur

**Comment by semuadmin** [comment]
Many thanks for reporting this - much appreciated. There was indeed a bug in mandelpycli which was causing the zyoffset to be fixed at 0.0. Should now be fixed in v1.0.5. Any further problems, don't hesitate to get back to me.
