### ISSUE TITLE
pymandelcli: Weird behavior with Gray Scale Theme at certain zoom level

### ISSUE THREAD

**Issue by 16flotho** [semuconsulting/PyMandel#3]
**Describe the bug**
I noticed a weird behavior when generating a Mandelbrot zoom with the `pymandelcli` and the Grayscale color theme. Somehow, the picture gets really messed up when it reaches a certain zoom level (see images below). I tried different zoom increments and zoom starting points (<1), but was always getting this weird blob (image 10).
The bug was not reproducible in the GUI.

**To Reproduce**
1. Run the command`pymandelcli filename="zoom" width=3840 height=1080 frames=50 zoom=0.7 zoominc=1.04 zxoffset=-1.401155189 zyoffset=0 theme="BasicGrayscale"`

**Screenshots**
Here are some images:
At the start of the generation, all looks fine:
![zoom_001](https://user-images.githubusercontent.com/55878563/222974509-8e78f352-70ad-49dd-9a3d-ec4058c9823e.png)

Then it gets progressively worse (Image 8 - 10). 
![zoom_008](https://user-images.githubusercontent.com/55878563/222974627-3fa997ef-787b-43e5-b869-4e2748b77cad.png)
![zoom_009](https://user-images.githubusercontent.com/55878563/222974630-c9b0d6ef-0a19-466e-bdb6-375758130c23.png)
![zoom_010](https://user-images.githubusercontent.com/55878563/222974632-c86ae185-65a3-42bf-b034-d1baadd9a216.png)

After that, the pictures slowly return to normal (Image 11 - 12)
![zoom_011](https://user-images.githubusercontent.com/55878563/222974846-ebee3351-e103-445b-b20e-e22dc1001ccf.png)
![zoom_012](https://user-images.githubusercontent.com/55878563/222974847-aef96142-3a5d-477d-9c1c-d4ec0268904f.png)

**Desktop:**
 - OS: Ubuntu 22.04
 - Version v1.0.8

**Comment by semuadmin** [comment]
Hi @16flotho 

I'll look into it - thanks for the report. May be a few weeks before I get around to a fix.

**Comment by 16flotho** [comment]
Very cool. Works now as expected. Thank you for your great work!
